version: '3.9'

services:
  postgres:
    image: "${POSTGRES_IMAGE:- postgres:15.3-bookworm}"
    volumes:
      - cursif-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD-postgres}"
      POSTGRES_HOST: "${POSTGRES_HOST:-localhost}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_DB: "${POSTGRES_DB:-cursif_dev}"

  backend:
    build:
      context: ./backend
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/
    ports: 
      - 8080:8080
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  cursif-data:
