version: '3.9'

services:
  postgres:
    image: "${POSTGRES_IMAGE:-postgres:15.3-bookworm}"
    volumes:
      - cursif-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app/
    ports:
      - 3000:3000
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  cursif-data:
